### ISSUE TITLE
Error in running the documented example

### ISSUE THREAD

**Issue by JafferWilson** [hosford42/pyramids#2]
I am getting issues in running your example:
```
> I am your friend.
========

Parse #1
Score: 0.8147313593151475 avg / 60.49815613599532 sum

Possible statement.
Graph:
sentence(aux,be,be_form,categorized,complete,cop,definite,finished_predicate,finished_verb,first,forward,grouped,has_object,has_subject,known_ending,present,singular,statement,takes_agent,takes_cause,takes_degree,takes_place,takes_purpose,takes_selection,takes_style,takes_time,terminated):
  I:
  *am:
    SUBJECT: I
    OBJECT: friend
    DELIMITER: .
  your:
  friend:
    SELECTOR: your
  .:

Root token: am
Root token position: 1
Root token category: verb(aux,be_form,cop,first,lower_case,present,singular)
Traceback (most recent call last):
  File "pyramids_parser_example.py", line 121, in <module>
    main()
  File "pyramids_parser_example.py", line 88, in main
    print("Root phrase category: %s" % graph.get_phrase_category(graph.root_index))
AttributeError: 'ParseGraph' object has no attribute 'get_phrase_category'

```

**Comment by hosford42** [comment]
I suspect you may be using an older version. I need to push the more recent changes to the Python Package Index. In the meantime, please try installing directly from git:

    pip install git+https://github.com/hosford42/pyramids.git

**Comment by JafferWilson** [comment]
Thank you Aaron. Yes, I got your point. I have check that after downloading your repository and running the example in it works... :)
